### ISSUE TITLE
Support path with Spaces

### ISSUE THREAD

**Issue by Saragani** [cristibalan/braid#110]
Assuming I have:
braid add --path "Remote Path/With Spaces" https://bitbucket.org/someProject/project.git "Local Path with Spaces/More path/with spaces"

Then the braid.json file is created/updated, but then it shows an error:
Braid: Shell error: usage: git remote add [<options>] <name> <url>

Currently my remote path doesn't have spaces, so I don't know if that's suported, but the error above happens with Local path with spaces.
If I use local path without spaces, then it works, but unfortunately, I do have spaces. I already tried \" and %20 and it didn't work.

**Comment by mattmccutchen** [comment]
Covered by #88.  You can add your "thumbs up" and any further comments there.  This wasn't high on my priority list, but if you can explain why you can't easily use a path without spaces, that might convince me.  Or we would accept a contribution if it's done well enough.
