### ISSUE TITLE
fork() function is unimplemented on this machine

### ISSUE THREAD

**Issue by my8bird** [cristibalan/braid#15]
It appears that braid is not windows friendly.  If that is the case and there is no plan to get working that is cool but please put a note on the front page.

If it is supposed to work let me know what information you need to debug this issue when running `braid list` in the root of my project.

A little history:
  My boss setup the project and started using braid to handle the deps, it works really really well, but he is using ubuntu.  I would like to add a new dep but this bug is currently stopping me.

**Comment by norbert** [comment]
As it's currently unknown which Ruby versions the current code does work with you should assume that only MRI on some kind of Unix is supported. @ttilley maybe you can clarify this?

Furthermore Windows support has always been a problem that won't be fixed and the documentation will be updated accordingly.
