### ISSUE TITLE
Braid: Error: local changes are present

### ISSUE THREAD

**Issue by millisami** [cristibalan/braid#16]
My repo was not clean and I stashed it. Couple of file are untracked.

When I issue the command:

`braid add git://github.com/fnichol/chef-rvm.git cookbooks/rvm`

It says, `Braid: Error: local changes are present`

And its weird. Do I have to remove or commit the untracked files as well? I think it should have been worked though I've untracked files, right?

**Comment by norbert** [comment]
This is caused by the way `git` is used interally and although it might not be clear why this happens, to me this behavior always made sense.

Anybody who might still be interested in solving this peculiarity should send a pull request.
