### ISSUE TITLE
Move All Code to Lib

### ISSUE THREAD

**Issue by yfeldblum** [cristibalan/braid#18]
There is a large quantity of code in `bin/braid`. My view is that large bins in gems are an anti-pattern.

Most of that code should be moved into `lib`. This is usually accomplished by making a class like `Braid::Cli` and sticking it into `lib/braid/cli.rb`. This file would typically not need to be required in `lib/braid.rb`. Instead, Both `braid` and `braid/cli` would be required in `bin/braid`.

Once all the code is moved into a class, the content of `bin/braid` would be just a set of `require`s and then a single line like `Braid::Cli.run(ARGV)`.

**Comment by norbert** [comment]
Even though your arguments are valid, the current layout has worked for many years now and will continue to do so.
