### ISSUE TITLE
Change summary and description in gemspec

### ISSUE THREAD

**Issue by norbert** [cristibalan/braid#23]
There should be a unique line of text used in the gemspec, in the README, for display on GitHub, and so forth. Who has a good suggestion?

/cc @cristibalan @realityforge + @mislav

**Comment by realityforge** [comment]
Hmm ... "Simple tool to help track vendor branches in a Git repository." is ok. Possible other alternatives include;
 
* "Vendor git repositories with pleasure"
* "Track git vendor repositories with pleasure"
* "Track git vendor branches, made easy"

But my brain is a little sleep deprived at the moment. Not sure I can think of any snappier taglines atm.

**Comment by norbert** [comment]
Proposal:

Summary:
Simple utility for tracking vendor branches in Git repositories.
Description:
Simple utility for tracking vendor branches in Git repositories using the subtree merge strategy.

Concise and to the point. Thoughts? Maybe "tool" is better than "utility" and so on.

**Comment by realityforge** [comment]
Works for me, although I prefer the word "tool"

**Comment by norbert** [comment]
Let's stick with "tool" then as that's been used for several years. Will make the necessary changes later.

**Comment by realityforge** [comment]
Looks like the decision was to keep it as is, so I am going to close this issue. Feel free to re-open if I got it wrong.
