### ISSUE TITLE
any plans to release something fresher than 2011?

### ISSUE THREAD

**Issue by mindreframer** [cristibalan/braid#26]
First of all, good that there is some activity on this project, I thought it has come to rest some time ago... 

Having last release in 2011 makes really suboptimal impression... Maybe we could release something working?
https://rubygems.org/gems/braid

VERSIONS:
0.7.1 - August 25, 2011 (27 KB)
0.7.0 - March 15, 2011 (26.5 KB)
0.6.2 - July 18, 2010 (26 KB)
0.6.1 - October 28, 2008 (26 KB)
0.6 - October 28, 2008 (25.5 KB)

even the current version would probably do... 

Cheers

**Comment by realityforge** [comment]
Recently a push has been made to try and get the next version of braid out based on the variant I was developing at https://github.com/realityforge/braid - until this is full released you can get the version it will look like at https://rubygems.org/gems/realityforge-braid 

Hopefully I will try and get a 1.0 out in main braid project soon. You can track this via #25

**Comment by realityforge** [comment]
Actually it turns out it was easy enough to release. So 1.0.0 has been released at https://rubygems.org/gems/braid

**Comment by mindreframer** [comment]
@realityforge Great, thx for releasing! Will now play with it!
