### ISSUE TITLE
Enable "GitHub Pages"

### ISSUE THREAD

**Issue by realityforge** [cristibalan/braid#27]
@cristibalan Can you enable "GitHub Pages" for the braid project. It is done via the settings page associated with the project. Then just auto-generate a site based on the README.md and select a style to go with it. Can you also add the target url as the website of the project. 

I am unable to do this and I believe only the owner of the project can do this.

Thanks!

**Comment by cristibalan** [comment]
Done! Thanks for the detailed steps.

Let me know if you prefer another the style template.

**Comment by realityforge** [comment]
Thanks!
