### ISSUE TITLE
document how it works

### ISSUE THREAD

**Issue by akostadinov** [cristibalan/braid#28]
I've found out that with `git` there is little hope to work efficiently without knowing what happens under the hood (at least not for a long time). Could you add a section how does `braid` work on the high level?

**Comment by norbert** [comment]
The answer is here: http://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging

Not sure this needs to be documented really.

**Comment by realityforge** [comment]
It probably does not need to be documented as such but I will try and add a pointer from our README to the git documentation when I get the time. Thanks for asking for this. (I also had to explain the exact same thing to someone at work recently)

**Comment by akostadinov** [comment]
Thanks, when I know it is subtree based, that allows for much better understanding whenever something goes wrong.

**Comment by realityforge** [comment]
Apparently the README is suffcient
