### ISSUE TITLE
Tracking other branches

### ISSUE THREAD

**Issue by YOUR1** [cristibalan/braid#29]
Is it possible to track a other branch while tracking master?

IE:
We are following branch REL1_23, and we want to update/merge it to REL1_24?

**Comment by norbert** [comment]
The `braid add` command allows you to specify which branch to track.

**Comment by YOUR1** [comment]
But you cannot specify --branch on braid update.

**Comment by realityforge** [comment]
If you just braid update it will update from the branch that it was initially added with. 

To change the branch I tend to delete the braid and then re-add it ... not sure if there is any easier way. 

Hope that helps!

**Comment by YOUR1** [comment]
Thank you for your answer Realityforge. But I don't think thats the right way for vendordropping.. Is there any chance this can be added as feature?

**Comment by realityforge** [comment]
It is a good idea and it wouldn't be that hard to do but I just don't have the bandwidth at the moment to do it. Maybe in the future.
