### ISSUE TITLE
"braid update" to tag, display tag/hash in "braid list"

### ISSUE THREAD

**Issue by tirolerstefan** [cristibalan/braid#31]
I think of using braid instead of submodules because it seems to be very helpful when using third party repos or subrepos.

Two things came in mind and I'd like to ask whether it's possible in future versions:

1) It would be very helpful to update the subtree to a tag instead of a hash, because the subrepo gets tagged when a stable state was reached.

2) It would be very helpful if I saw the hash (or tag) when invoking <braid list>, so I don't need to open .braids or consult the git log.

**Comment by realityforge** [comment]
Good ideas. Using tags would be *very* useful and I looked at doing a while back but it did not seem like 5 minutes work and I have never got back to it. Next time I work on this I will look into it again.

Otherwise we gladly accept pull requests ;)

**Comment by realityforge** [comment]
I finally got around to implementing this in version `1.0.18` of the gem. You can track a particular tag via a command like `braid add https://github.com/realityforge/backpack.git vendor/tools/backpack  --tag v1.0`. You can also revert it to tracking a branch at a later point by the command `braid update vendor/tools/backpack --branch master`.

The `braid status` or  `braid status vendor/tools/backpack` command will tell you the current tracking mechanism (i.e. tracking a branch, a tag or locked to a revision).

Hope that helps. Better late than never ;)
