### ISSUE TITLE
braid swallows git fetch errors, even in verbose mode

### ISSUE THREAD

**Issue by rsutphin** [cristibalan/braid#5]
If you try to add a braid and there is an error during `git fetch`, braid will not tell you what it is, even if you turn on verbose mode.  This makes determining why braid isn't working harder than it needs to be.

Example:

    $ braid add git://git.apache.org/buildr.git vendor/buildr -v
    Braid: Executing `git --version`
    Braid: Executing `git status`
    Braid: Executing `git rev-parse HEAD`
    Braid: Adding git mirror of 'git://git.apache.org/buildr.git'.
    Braid: Executing `git --version`
    Braid: Executing `git config remote.braid/vendor/buildr.url`
    Braid: Executing `git config svn-remote.braid/vendor/buildr.url`
    Braid: Setup: Creating remote for 'vendor/buildr'.
    Braid: Executing `git remote add -t master -m master braid/vendor/buildr /Users/rsutphin/.braid/cache/git___git.apache.org_buildr.git`
    Braid: Executing `git config remote.braid/vendor/buildr.url`
    Braid: Executing `git fetch  2>&1 >/dev/null`
    Braid: Executing `git fetch -n braid/vendor/buildr 2>&1 >/dev/null`
    Braid: Resetting to 'b3eca84'.
    Braid: Executing `git reset --hard b3eca84da9af3175978d05d59461ca3cbecce6c9`
    Braid: Shell error: could not fetch

By modifying braid to remove the redirects to `/dev/null` I was able to track the problem down (apache git mirrors don't have a "master" branch, so I needed to specify a branch explicitly), but it took a while to get there.  If the full fetch output were provided in verbose mode (or, better, whenever there was an error), the problem would have been clear right away.

**Comment by norbert** [comment]
This would be helpful but it's not something that's ever been a problem for me.
