### ISSUE TITLE
[question] Partial checkout?

### ISSUE THREAD

**Issue by LiraNuna** [cristibalan/braid#52]
Is partial checkout a supported use case? My use case needs a single directory from the imported repo and not the whole thing. I cannot find anything in the docs about this (maybe I'm missing this).

Help would be appreciated!

**Comment by realityforge** [comment]
It should be relatively easy to implement but braid does not yet have support this scenario.

**Comment by LiraNuna** [comment]
Then consider this an enhancement request!

**Comment by realityforge** [comment]
Add mechanisms to do this in version 1.0.16. See https://github.com/cristibalan/braid#adding-a-subdirectory-from-a-mirror for some very basic documentation on how to do it. 

If you hit any issues feel free to report a bug.

**Comment by realityforge** [comment]
Just a note. I went and reworked this feature slightly the parameter changed to `--path` on the command line and `path` in `.braids.json` and released it as 1.0.17. Also added a bunch more tests and are now happy with the functionality
