### ISSUE TITLE
[question] braid push to a different branch?

### ISSUE THREAD

**Issue by LiraNuna** [cristibalan/braid#53]
I'm wondering if it's possible to push changes using `braid push` to a different branch (that is not in the `.braids` file)?

The use case is to submit a pull-request which plays nicely with code reviews.

**Comment by realityforge** [comment]
It would be a very useful addition but it has not been implemented. Locally we still use the `braid diff > patch` + `git apply patch` approach. 

I have often thought about extending braid to use hub (https://github.com/github/hub) to generate the pull request. Braid already creates a separate temp git directory to do it's work, it would not take much to get it pushing to a separate branch (via a command line switch to push?) or even launching the hub command to actually generate the pull request.

But alas it is not implemented. I may try to investigate how hard it would be to optionally push to a separate branch as configured on the command line.

**Comment by LiraNuna** [comment]
As a fellow `hub` user, it would be a great addition, as long as it would still be possible to accommodate non-github repos (ideally using the separate branch approach)

**Comment by realityforge** [comment]
Ok had a go at implementing this and it turns out it was relatively easy. See commit 91f233610091a796c4e1279da97b1ec0d2fdc346 - I will try and release 1.0.14 in the next hour or so
