### ISSUE TITLE
Push tests fail locally if global user.{name,email} are unset

### ISSUE THREAD

**Issue by mattmccutchen** [cristibalan/braid#57]
When I run the test suite in my VM with global `user.name` and `user.email` unset, the push tests fail.  I see these settings were added to the `.travis.yml`.  We could document that these settings have to be set in order to run the test suite locally (which would mean I'd do my Braid development in a different VM) or perhaps find another workaround.  But I wonder if having `braid push` use the global settings might be a poor design in the first place.  What does the user expect?  Should we use the author settings from the repository in which `braid push` was invoked (which would be a matter of copying the settings to the temporary repository)?  For that matter, I can probably rewrite `braid push` so it generates a temporary commit in the original repository without touching the working tree (hooray for git plumbing commands), and that would also solve the problem.

**Comment by realityforge** [comment]
I like the idea of copying the settings if they exist from the repository in which push was invoked. I think that makes the most sense from the users perspective. 

While it would be possible to do it within a temporary repository - I like the idea of doing it in a temporary directory as it at least gives us the ability to run other commands (i.e. `hub`) if/when we decide to integrate with them down the track.
