### ISSUE TITLE
Support a mirror consisting of a single file

### ISSUE THREAD

**Issue by mattmccutchen** [cristibalan/braid#64]
If the remote path for a mirror points to a single file, Braid should create a mirror consisting of the single file at the specified local path.

The use case that came up for me today: applying a gitignore file from https://github.com/github/gitignore to one's own repository.  (The GitHub new repository wizard has an option to copy the gitignore file.  The coup would be if I can get GitHub to add a checkbox to create .braids.json; it would be a great way to advertise a tool that I think a lot more people could benefit from using.)

This is mostly a matter of changing all the spots in the code that assume that `Mirror::versioned_path` returns a tree to also handle blobs.  (Arguably, it's unfortunate that this is a special case at all, but that's beside the point.)  The only interesting issue I see is what filenames `braid diff` should output.  The current code that calls `git diff --relative=MIRROR_PATH` produces just `a/` and `b/`, which makes sense in a way but might break tools.  It's probably reasonable to use the basename of the file, but the upstream or downstream basename?  They might differ, as in the gitignore use case above.  [Thoughts, @realityforge?]  Edit: My proposal: use `a/UPSTREAM_NAME` and `b/DOWNSTREAM_NAME`.

**Comment by realityforge** [comment]
Seems fairly reasonable to me. It seems like something that could get broken a long the way if we don't have have good test coverage but as long as we have that then I think we are good.
