### ISSUE TITLE
Braid doesn't honor revision locks from Braid < 1.0.18

### ISSUE THREAD

**Issue by mattmccutchen** [cristibalan/braid#65]
A while ago, I [locked several mirrors to particular revisions](https://bitbucket.org/objsheets/objsheets/src/8cb646bc8dc58a27e5608ac1169bb9f653c7a9e9/.braids?at=master&fileviewer=file-view-default), which Braid then represented using the `lock` field.  e6535aa changed the way a revision lock is represented and didn't keep support for reading the old format.  So Braid would now update these mirrors to the latest commit on the branch if I let it.  Was this intentional?  I guess the damage may already be done for many users, but we could add the proper code now to read the old format.  We need to get better at compatibility if we want people to take Braid seriously.

**Comment by realityforge** [comment]
The change was not intentional but I think I was committing in a particularly sleep deprived state so it may have slipped by. We could  detect the old format and try to migrate format but I don't have the cycles atm to make it happen.
