### ISSUE TITLE
Line breaking at char #80?

### ISSUE THREAD

**Issue by giovannisaraceno** [cristibalan/braid#80]
When I add a lib and then I check the diffs with `braid diff lib/x` it seems to break the lines above 80 chars and rearrange the code.

I work in typescript so I have a common limit to 140 chars, so there are a lot of diffs only for these line breakings. It's a bug or there's an option to avoid this issue?

Ty

**Comment by mattmccutchen** [comment]
This shouldn't be happening.  Complete steps to reproduce?

**Comment by giovannisaraceno** [comment]
It seemed fixed readding the repositories... Weird O.o

**Comment by mattmccutchen** [comment]
Let us know if the problem occurs again and you have steps to reproduce it.
