### ISSUE TITLE
doc: clarify version control use

### ISSUE THREAD

**Issue by phromo** [cristibalan/braid#83]
Perhaps I'm approaching braid with the wrong assumptions, but could you update the docs to clarify what I'm supposed to version control and what I'm suppossed to gitignore?

Should i put the added repo files under gitignore or should I make commits? Should I version `.braids.json` or is it supposed to be developer-local?

If it's not local, what's the command to restore the working directory based on a `.braids.json`?

**Comment by realityforge** [comment]
`braid` takes the contents of a remote repository and adds them to the local repository. The tool itself will add and commit the remote branch as well as the `.braids.json` file.

The best way to understand the tool is to run through the Quick usage section of docs and look at what it does to the repository. HTH
